#!/bin/bash

# Funciona apenas apartir de qualquer distro baseada no ubuntu 22.04 pra cima.

echo "==============================="
echo " Bem-vindo ao Auto-Palera1n!"
echo "==============================="
echo "Voce escolheu o iOS $1"
echo "Digite 1 para iniciar ou 0 para sair"
read resp
if [ $resp -eq 1 ]
 then
   echo -e "\033[0;37m[*] Instalando Dependencias pode demorar um pouco..."
   sudo apt update > /dev/null
   sudo apt install git -y > /dev/null
   sudo apt-get install sudo gcc bash xterm wget python3-pip libusb-1.0-0 libusb-1.0-0-dev libadolc2 libusbmuxd-tools libtool libtool-bin autoconf automake libimobiledevice* make -y > /dev/null
   sudo pip install pyimg4 &> /dev/null
   wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb &> /dev/null
   wget https://github.com/CoocooFroggy/FutureRestore-GUI/releases/download/v1.98.2/FutureRestore-GUI-Debian-1.98.2.deb &> /dev/null
   sudo apt install ./libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb -y > /dev/null
   sudo apt install ./FutureRestore-GUI-Debian-1.98.2.deb -y > /dev/null
   git clone https://github.com/tihmstar/libgeneral &> /dev/null
   cd libgeneral
   printf "\n[*] Compilando LIBGENERAL...\n\n"
   sudo ./autogen.sh &> /dev/null
   sudo make &> /dev/null
   sudo make install &> /dev/null
   cd ..
   git clone https://github.com/tihmstar/usbmuxd2 &> /dev/null
   cd usbmuxd2
   printf "\n[*] Compilando USBMUXD2...\n\n"
   sudo ./autogen.sh &> /dev/null
   make &> /dev/null
   make install &> /dev/null
   printf "\n[+] Dependencias instaladas!\n"
   sleep 1
   systemctl stop usbmuxd
   xterm -e bash -c 'printf "Por favor nao feche esta janela!\n\n"; usbmuxd -f -p; read' &
   cd ..
   echo -e "\n[*] Baixando Palera1n...\n"

   git clone https://github.com/palera1n/palera1n &> /dev/null
   cd palera1n
   #printf "\033[0;32m[+] Digite sua versao do iOS ex: 16.1 \n"
   #read iosv
   printf "\033[1;37m[*] Conecte seu aparelho e espere e siga os procedimentos a baixo\n"
   sudo ./palera1n.sh --tweaks $1
else
   echo "[*] Saindo..."
   exit
fi
